@startuml
actor Atendente
participant "Sistema" as S

Atendente -> S: Inserir nome e CPF do cliente
S -> S: Verificar cliente e buscar pedido
alt Cliente não encontrado
    S -> Atendente: Exibir erro
end
alt Sem pedidos pendentes
    S -> Atendente: Informar ausência de pedidos
end
S -> Atendente: Exibir pedido

Atendente -> S: Solicitar cálculo total
S -> S: Calcular valor total
S -> Atendente: Exibir total
@enduml
